### ISSUE TITLE
Add cocoapods_version = '>=1.9' to FirebaseFirestore.podspec

### ISSUE THREAD

**Issue by jmagman** [invertase/firestore-ios-sdk-frameworks#1]
CocoaPods didn't support XCFrameworks until [1.9.0](https://blog.cocoapods.org/CocoaPods-1.9.0-beta/).  Add [`cocoapods_version = '>=1.9'`](https://guides.cocoapods.org/syntax/podspec.html#cocoapods_version) to the FirebaseFirestore.podspec.

Flutter's minimum required CocoaPods version is 1.6.0 with a recomendation of 1.8.0.

**Comment by Salakar** [comment]
I knew I forgot something :see_no_evil: thanks for reporting 

I'll get this added and will look at redoing the tags so its applied all the way back as part of fixing #2
