### ISSUE TITLE
Build fail to IOS 7.1.0

### ISSUE THREAD

**Issue by FranGhe** [invertase/firestore-ios-sdk-frameworks#101]
Hi, I'm developing by cordova-ios 7.1.0 and I have this trouble.

**mac version** 
macOS Sonoma 14.4.1 (23E224)

**xcode version** 
version 15.2

**Pod Version**
1.15.2

**iOS SDKs**
iOS 17.2 -sdk iphoneos17.2

**cordova platform**
ios 7.1.0

I starts to build my project and it fails with errors on compiling firebase::firestore with errors:
> ld: **Undefined symbols**:
>   absl::lts_20240116::numbers_internal::FastIntToBuffer(int, char*), referenced from:
>       absl::lts_20240116::AlphaNum::AlphaNum(int) in FirebaseFirestoreInternal [68] (FIRDocumentChange.o)
>   absl::lts_20240116::numbers_internal::FastIntToBuffer(long long, char*), referenced from:
>       absl::lts_20240116::AlphaNum::AlphaNum(long long) in FirebaseFirestoreInternal [86] (FIRFirestoreSettings.o)
>   absl::lts_20240116::numbers_internal::FastIntToBuffer(unsigned long long, char*), referenced from:
>       absl::lts_20240116::AlphaNum::AlphaNum(unsigned long) in FirebaseFirestoreInternal [41] (document_key.o)
>       absl::lts_20240116::AlphaNum::AlphaNum(unsigned long long) in FirebaseFirestoreInternal [103] (FSTUserDataReader.o)
>   absl::lts_20240116::numbers_internal::SixDigitsToBuffer(double, char*), referenced from:
>       absl::lts_20240116::AlphaNum::AlphaNum(double) in FirebaseFirestoreInternal [89] (FIRGeoPoint.o)
>   absl::lts_20240116::optional_internal::throw_bad_optional_access(), referenced from:
>       -[FIRDocumentSnapshot initWithFirestore:documentKey:document:metadata:] in FirebaseFirestoreInternal [70] (FIRDocumentSnapshot.o)
>       std::__1::__function::__func<firebase::firestore::core::FirestoreClient::GetDocumentsFromLocalCache(firebase::firestore::api::Query const&, std::__1::unique_ptr<firebase::firestore::core::EventListener<firebase::firestore::api::QuerySnapshot>, std::__1::default_delete<firebase::firestore::core::EventListener<firebase::firestore::api::QuerySnapshot>>>&&)::$_16, std::__1::allocator<firebase::firestore::core::FirestoreClient::GetDocumentsFromLocalCache(firebase::firestore::api::Query const&, std::__1::unique_ptr<firebase::firestore::core::EventListener<firebase::firestore::api::QuerySnapshot>, std::__1::default_delete<firebase::firestore::core::EventListener<firebase::firestore::api::QuerySnapshot>>>&&)::$_16>, void ()>::operator()() in FirebaseFirestoreInternal [79] (firestore_client.o)
>       std::__1::__function::__func<firebase::firestore::core::FirestoreClient::GetNamedQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::function<void (firebase::firestore::core::Query, bool)>)::$_27, std::__1::allocator<firebase::firestore::core::FirestoreClient::GetNamedQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::function<void (firebase::firestore::core::Query, bool)>)::$_27>, void ()>::operator()() in FirebaseFirestoreInternal [79] (firestore_client.o)
>       std::__1::__function::__func<std::__1::enable_if<!std::is_same<void, decltype(fp0())>::value, decltype(fp0())>::type firebase::firestore::local::Persistence::Run<firebase::firestore::local::LocalStore::RejectBatch(int)::$_6>(absl::lts_20240116::string_view, firebase::firestore::local::LocalStore::RejectBatch(int)::$_6)::'lambda'(), std::__1::allocator<std::__1::enable_if<!std::is_same<void, decltype(fp0())>::value, decltype(fp0())>::type firebase::firestore::local::Persistence::Run<firebase::firestore::local::LocalStore::RejectBatch(int)::$_6>(absl::lts_20240116::string_view, firebase::firestore::local::LocalStore::RejectBatch(int)::$_6)::'lambda'()>, void ()>::operator()() in FirebaseFirestoreInternal [143] (local_store.o)
>       firebase::firestore::local::QueryEngine::GetDocumentsMatchingQuery(firebase::firestore::core::Query const&, firebase::firestore::model::SnapshotVersion const&, firebase::firestore::immutable::SortedSet<firebase::firestore::model::DocumentKey, firebase::firestore::util::Comparator<firebase::firestore::model::DocumentKey>> const&) const in FirebaseFirestoreInternal [181] (query_engine.o)
>       firebase::firestore::local::QueryEngine::PerformQueryUsingIndex(firebase::firestore::core::Query const&) const in FirebaseFirestoreInternal [181] (query_engine.o)
>   absl::lts_20240116::StrCat(absl::lts_20240116::AlphaNum const&, absl::lts_20240116::AlphaNum const&, absl::lts_20240116::AlphaNum const&), referenced from:
>       firebase::firestore::core::Query::ToString() const in FirebaseFirestoreInternal [178] (query.o)
>       firebase::firestore::core::Query::CanonicalId() const in FirebaseFirestoreInternal [178] (query.o)
>   absl::lts_20240116::StrAppend(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, absl::lts_20240116::AlphaNum const&, absl::lts_20240116::AlphaNum const&), referenced from:
>       -[FSTFirestoreComponent firestoreForDatabase:] in FirebaseFirestoreInternal [102] (FSTFirestoreComponent.o)
>   absl::lts_20240116::string_view::find(absl::lts_20240116::string_view, unsigned long) const, referenced from:
>       -[FIRQuery boundFromFieldValues:isInclusive:] in FirebaseFirestoreInternal [94] (FIRQuery.o)
> **clang: error: linker command failed with exit code 1 (use -v to see invocation)**

This is my Podfile on Xcode:
> source 'https://cdn.cocoapods.org/'
> platform :ios, '12.0'
> use_frameworks!
> target 'Cortona' do
> 	project 'Cortona.xcodeproj'
> 	pod 'FirebaseCore', '10.24.0'
> 	pod 'FirebaseAuth', '10.24.0'
> 	pod 'FirebaseAnalytics', '10.24.0'
> 	pod 'FirebaseMessaging', '10.24.0'
> 	pod 'FirebasePerformance', '10.24.0'
> 	pod 'FirebaseRemoteConfig', '10.24.0'
> 	pod 'FirebaseInAppMessaging', '10.24.0-beta'
> 	pod 'FirebaseFirestore', :tag => '10.24.0', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'
> 	pod 'FirebaseCrashlytics', '10.24.0'
> 	pod 'FirebaseFunctions', '10.24.0'
> 	pod 'FirebaseInstallations', '10.24.0'
> 	pod 'GoogleSignIn', '6.2.4'
> 	pod 'GoogleTagManager', '7.4.6'
> end
> 
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
>             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
>             if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
>                 config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>             end
>         end
>     end
> end

I tried to edit the FirebaseFirestore version to 10.25.0 on my Xcode Podfile and launch again the build, but it fails with the same issues.

Any ideas? 

Thanks

**Comment by russellwheatley** [comment]
I have no experience on Cordova I'm afraid. Might be worth opening an issue on StackOverflow and see if you can get some help there.
