### ISSUE TITLE
Support Apple Silicon ARM simulators

### ISSUE THREAD

**Issue by jmagman** [invertase/firestore-ios-sdk-frameworks#16]
The simulator binary is missing the arm64 slice needed to run on Apple Silicon arm64 simulators.  

```
ios-i386_x86_64-simulator/FirebaseFirestore.framework/FirebaseFirestore: Mach-O universal binary with 2 architectures: [i386:current ar archive] [x86_64]
ios-i386_x86_64-simulator/FirebaseFirestore.framework/FirebaseFirestore (for architecture i386):	current ar archive
ios-i386_x86_64-simulator/FirebaseFirestore.framework/FirebaseFirestore (for architecture x86_64):	current ar archive
```
I think it creates a `ios-arm64_x86_64-simulator` directory in the bundle though I'm not 100% sure on the name.

**Comment by jmagman** [comment]
Note CocoaPods currently has `ffi` issues https://github.com/CocoaPods/CocoaPods/issues/9907.  You can test by directly embedding the xcframework, targeting a simulator, and swap `ONLY_ACTIVE_ARCH` to `NO`.

**Comment by Salakar** [comment]
Tracking upstream; https://github.com/firebase/firebase-ios-sdk/issues/6520

**Comment by mikehardy** [comment]
@jmagman I think this may work now, the upstream issue is closed. Can you confirm current status with current version (v7.2.0 should work but v7.3.0 just came out and is current now)
