### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FirebaseFirestore":

### ISSUE THREAD

**Issue by MockAirplane700** [invertase/firestore-ios-sdk-frameworks#17]
I am trying to run an app IOS that is dependent on cloud fire store. The app installs but crashes immediately. When I run pod install I get the error "CocoaPods could not find compatible versions for pod "FirebaseFirestore":In Podfile:" I have already tried pod update, deleting the pod.lock file and other similar solutions online. Please find the full error message below:
[!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `7.1.0`)
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.3, which depends on
      Firebase/Firestore (~> 6.33.0) was resolved to 6.33.0, which depends on
        FirebaseFirestore (~> 1.18.0)

Steps to reproduce:
run pod instal --repo-update

The pod file contents are below:
```ruby
# Uncomment this line to define a global platform for your project
 platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}



def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

   pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.1.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

# add the Firebase pod for Google Analytics
```

**Comment by mikehardy** [comment]
It appears cloud_firestore wants firebase-ios-sdk 6.34.0 versions, but you are attempting to use the precompiled 7.1.0 version from here. You should try the 6.34.0 version from here?

```ruby
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.34.0'
```

**Comment by MockAirplane700** [comment]
Thank you I was able to run the pod install but however when I run the app it crashes on launch

**Comment by mikehardy** [comment]
Hmm without a crash trace I assume this has nothing to do with the framework, sorry. If this framework installs, it will work the same as the release from firebase-ios-sdk, so support should be obtained from your normal software stack. Information you'll need will be the crash trace you see in the Xcode console after attempting to start the app after building and deploying it from Xcode, but the root cause won't be here. That info should point out where to go though

**Comment by MockAirplane700** [comment]
thank you I appreciate it
