### ISSUE TITLE
No such module 'FirebaseCore' with 6.34.0 and 7.1.0

### ISSUE THREAD

**Issue by FaultyJuggler** [invertase/firestore-ios-sdk-frameworks#18]
Hello, after running into a lot of problems with cocoapods-binary I was hoping this would be an alternative to reduce the massive build complexity this exists to address.  My project was running fine without prebuilds, I swapped out FirebaseFirestore for this and tried both 6.34.0 and 7.1.0 but both times when I try to build it says

`No such module 'FirebaseCore'`

I also couldn't import regular Firebase.
I had this import so I could call
`FirebaseApp.configure()`

Is there a way to call this differently with just FirebaseFirestore that I'm not aware of?

**Comment by mikehardy** [comment]
Are you by chance using Xcode 12.2? I have a semi-related report about 'React-Core' vs 'ReactCore' in the apple sign in repo

One thing I will mention just for word precision is that this does nothing to address build complexity in the way most people mean it, as a synonym of complications. It does reduce complexity in the sense of simply reducing the amount of work to be done.

But if your build is not running with the regular Firestore pod, this will likely not help it and may even cause issues with e.g. Apple Silicon compiles.

Most of that is just context though.

Actual thoughts: with no podfile presented, I'm not sure why it's not working. I can say that for react-native at least, it's been working fine. I'm not aware of any issues with the FlutterFire development crew either, so this sounds project-specific in some way

You have probably already tried a `pod repo update`, but you may not have tried just purging your whole `$HOME/.cocoapods` (I think that's the path...) directory, perhaps that could help but those are long shots.

**Comment by FaultyJuggler** [comment]
@mikehardy you are correct sir, xcode 12.2, and my bad for not including my podfile, thought it's pretty simple

```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Affiliate-extension
  pod 'RealmSwift'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.1.0'

end

target 'CashBack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'RealmSwift'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.1.0'
  pod 'GoogleSignIn'#, '<=5.0.2'


end


post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
             config.build_settings['EXCLUDED_ARCHS[sdk=watchsimulator*]'] = 'arm64'
             config.build_settings['EXCLUDED_ARCHS[sdk=appletvsimulator*]'] = 'arm64'
             config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
             config.build_settings['ENABLE_BITCODE'] = 'NO'
         end
     end
 end

```

**Comment by bermanapps** [comment]
I have exactly the same issue, any progress with this?

**Comment by mikehardy** [comment]
@bermanapps it's not reproducible, I don't see any problem I can reproduce, thus no progress as it appears to be working. Test harness to back assertion - executed against Xcode 12.2 many times now: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by bermanapps** [comment]
I'm using xcode 12.2, and **flutter**. In pubspec.yaml in dependancies is have:
 cloud_firestore: ^0.14.3

Then in podfile I put:

 pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.1.0'

I still get error
 [!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
      In Podfile:
        FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `7.1.0`)

        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.3, which depends on
          Firebase/Firestore (~> 6.33.0) was resolved to 6.33.0, which depends on
            FirebaseFirestore (~> 1.18.0)

[WIth more details, but I didn't want to post the entire long error. I will if you want]

Thanks

**Comment by mikehardy** [comment]
That's probably because FlutterFire doesn't work with v7 yet. I'm actually looking into porting that now.
Use the same tag that FlutterFire uses, should be 6.33.0. They **must** match. That's the problem, it will fix you

**Comment by rhisiart-cufflink** [comment]
I haven't bumped the version beyond 6.33 yet and won't unless I need to but for what it's worth, I'm using the following and all seems OK:

```
  cloud_firestore: ^0.14.2
  cloud_functions: ^0.6.0+1
  firebase_auth: ^0.18.2
  firebase_messaging: ^7.0.3
```

```
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Speed up iOS build https://github.com/FirebaseExtended/flutterfire/issues/2751
  # https://github.com/invertase/firestore-ios-sdk-frameworks
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.33.0'  
end
```

```
Xcode 12.2
Build version 12B45b

Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (11 days ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

cocoapods (1.10.0)
```

**Comment by mikehardy** [comment]
Thanks for the success report! With FlutterFire on 6.33.0 I expect that should work, so I'm glad to hear it does

Mostly replying to say when the forward-port to firebase-ios-sdk v7.1.0 and firebase-android-sdk v26.1.0 is ready you'll probably want to move - at least for messaging there is firebase-ios-sdk token issue where on first install cloud messages don't work, you have to close the app and re-run it before they work, which is not a great experience for first installs if your app uses messaging. In general always best to use the latest upstream SDKs but obviously only once supported by FlutterFire. Hopefully soon
