### ISSUE TITLE
RN 0.64.3 and duplicate [CP] Prepare Artifacts build phase causing errors

### ISSUE THREAD

**Issue by andersonaddo** [invertase/firestore-ios-sdk-frameworks#20]
Has anyone been able to build an emulator app using react-native-firebase and firestore-ios-sdk-frameworks on react-native 0.63.4? I haven't been able to (well, I haven't been able to seamlessly).

Here's my environment:
```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 30.86 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/andersonaddo/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Due to [some the changes](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.63.4
) that I had to implement when upgrading, my podfile now looks like this:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'

project 'app',
        'Dev.Debug' => :debug,
        'Dev.Release' => :release, 
        'Prod.Debug' => :debug,
        'Prod.Release' => :release

target 'app' do
  # Pods for app
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.3.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  # Pods for react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(configurations: ['Dev.Debug', 'Prod.Debug'])
  post_install do |installer|
    flipper_post_install(installer)
  end

end
```
One notable difference this podfile has from its predecessor is that the inherit mode in the "appTests" target has moved from `inherit! :search_paths` to `inherit! :complete`.

I think because of this, I'm getting this error when attempting to build from xcode:
```
Multiple commands produce '/Users/andersonaddo/Library/Developer/Xcode/DerivedData/app-brcjfkvaegkdwhfoswuqsjdgdpga/Build/Products/Prod.Debug-iphonesimulator/cocoapods-artifacts-Prod.Debug.txt':
1) That command depends on command in Target 'app' (project 'app'): script phase “[CP] Prepare Artifacts”
2) That command depends on command in Target 'appTests' (project 'app'): script phase “[CP] Prepare Artifacts”
```
And alas, the [CP] Prepare Artifacts script looks like this:
<img width="695" alt="Screen Shot 2021-01-09 at 1 56 15 AM" src="https://user-images.githubusercontent.com/34724755/104080076-ef76c680-521d-11eb-9e78-b20f6aedbeb5.png">

And this phase is in both targets, hence the error.
I think it has to do with the `inherit! :search_paths` vs `inherit! :complete` change, but I also think that if this was a problem others were facing  it would've been mentioned somewhere, no?

**Comment by mikehardy** [comment]
Hey @andersonaddo 

I feel like I have

I (temporarily) de-integrated it on RNFB https://github.com/invertase/react-native-firebase/blob/b4fb97698eb2579da3937bc6fed5dc4267f56aa1/tests/ios/Podfile#L15 but that was from leveldb collisions on local compiles, it actually worked in CI and it is react-native 0.63.4 https://github.com/invertase/react-native-firebase/blob/b4fb97698eb2579da3937bc6fed5dc4267f56aa1/tests/package.json#L28 - you should get try out the tests project to verify it locally

My work project is on react-native 0.63.4 and uses it successfully

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % cat package.json |grep "\"react-native\""
    "react-native": "^0.63.4",
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % cat ios/Podfile|grep 'sdk-frameworks'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion

```

The only issues I've seen are leveldb collisions :thinking:

**Comment by mikehardy** [comment]
Wait a second there - you are on an old Xcode, that's a cardinal sin man :-). Xcode "current stable" is a general requirement for iOS development at all times, and you'll likely want cocoapods 1.10 as well - same general expectation.

The last iOS release + Xcode release was fairly abrupt in fact with some breaking changes and not much warning on the release with Apple Silicon support and a bunch of new APIs, those things have to be adopted almost immediately or you can't access the App Store. In general that "adopt new APIs or App Store rejects you", "Have to update Xcode so you can adopt APIs" drives the requirement of Xcode updates which creates that general dev expectation that it's up to date

I bet that fixes it

**Comment by andersonaddo** [comment]
Thanks for the reply Mike. Will definitely update my stuff and check back. 

I'm skeptical that will fix this particular error though; one thing I noticed about your linked podfile is that RNFB doesn't configue a test target. It looks like the Xcode project will have only the main app target - hence no duplicate build phases and no errors. 

I think I can disable the test target and do away with the error. I don't think it's useful either; RN just comes with it by default. But the fact that it's there by default (I'm guessing you've heavily edited the RNFB test podfile from the default?) is what made me make this issue as I surmised others would face this problem as well.

**Comment by mikehardy** [comment]
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh specifically does not edit from default other than to slice in RNFB :smile: 

However, it does disable frameworks for leveldb errors. If you edit that script to exclude the database module, you should be able to get around the leveldb issues and see if it reproduces with standard react-native template

**Comment by andersonaddo** [comment]
Right, I'll put that on my pile of things to do. Will get back to ya in a lil bit.

**Comment by andersonaddo** [comment]
Did my investigations; your script (unsurprisingly, haha) was a big help.
![giphy](https://user-images.githubusercontent.com/34724755/104828994-2318a880-583d-11eb-9782-c232253bf913.gif)
It was due to me having an outdated CocoaPods.

**Comment by mikehardy** [comment]
cocoapods 1.10 (vs 1.9 causing problems) has shown itself to be needed for a variety of things. This could be in a FAQ or even on a minimum versions page as a strong suggestion maybe. It caught a few people out in the Notifee repo as well, you are not alone! Glad the demo script helped

**Comment by paulb777** [comment]
You could update the `cocoapods_version` in the podspec to enforce the 1.10 requirement at install time.

**Comment by mikehardy** [comment]
@paulb777 of course - good idea
