### ISSUE TITLE
Question - Position of the line to add in podfile for flutter project

### ISSUE THREAD

**Issue by pawanRVT** [invertase/firestore-ios-sdk-frameworks#25]
Hi, 

A question on where the line should be added in the podfile in the flutter project.
I have added the line towards the end in the runner do block. Is this correct?
`
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.3.0'
end
`

**Comment by mikehardy** [comment]
I would follow the example? It is known to work.

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/ios/Podfile

**Comment by pawanRVT** [comment]
Thanks Mike
