### ISSUE TITLE
Podspec missing requirements specified by upstream Firestore podspec, causes build failures

### ISSUE THREAD

**Issue by ben-xD** [invertase/firestore-ios-sdk-frameworks#29]
I was following the getting started guide, which has an improve [ios build times section](https://firebase.flutter.dev/docs/overview/#improve-ios-build-times): So I added the `pod 'FirebaseFirestore'` line.  I tried it with different versions: 6.26.0 as documented there, 7.3.0 (as according to the readme on this page) and 7.8.1 (the newest version), they all have the same errors below:

I get 2 different errors (1 for simulators, and one for my real iPhone): I pasted it here but it was too big, so I've attached txt files:

## iPhone 12 build output error

[real.txt](https://github.com/invertase/firestore-ios-sdk-frameworks/files/6175910/real.txt)
Most relevant:
```
Error output from Xcode build:
↳
    2021-03-20 15:55:59.670 xcodebuild[40159:398433] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
    ** BUILD FAILED **
```

## iPhone 12 simulator build output error

[sim.txt](https://github.com/invertase/firestore-ios-sdk-frameworks/files/6175927/sim.txt)

```
Xcode's output:
↳
    Undefined symbols for architecture x86_64:
      "std::__1::to_string(long)", referenced from:
          grpc_core::channelz::ChannelNode::RenderJson() in gRPC-Core(channelz.o)
          grpc_core::channelz::ChannelNode::PopulateChildRefs(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, grpc_core::Json, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, grpc_core::Json> > >*) in gRPC-Core(channelz.o)
          grpc_core::channelz::ServerNode::RenderServerSockets(long, long) in gRPC-Core(channelz.o)
          grpc_core::channelz::ServerNode::RenderJson() in gRPC-Core(channelz.o)
          grpc_core::channelz::SocketNode::RenderJson() in gRPC-Core(channelz.o)
          grpc_core::channelz::ListenSocketNode::RenderJson() in gRPC-Core(channelz.o)
          grpc_core::channelz::ChannelTrace::TraceEvent::RenderTraceEvent() const in gRPC-Core(channel_trace.o)
          ...
```

**Comment by mikehardy** [comment]
Hi there!
WIthout knowing anything about your setup, I can't say why this is not working.
I can say that we build using it all the time, and it works fine in a reproducible way, so from our perspective it is working.

https://github.com/invertase/react-native-firebase/runs/2151957879?check_suite_focus=true#step:16:55

If you can share a minimal reproducible example on github that allows us to reproduce the issue, then we can triage more

**Comment by paulb777** [comment]
A workaround might be explicitly linking the C++ standard library:

![Screen Shot 2021-03-20 at 9 29 18 AM](https://user-images.githubusercontent.com/73870/111877087-da758c80-895e-11eb-8291-d619151f60bb.png)

**Comment by mikehardy** [comment]
@paulb777 just to be clear (and to learn a bit, for me) - is that a recommendation for the original poster or is this something that we should maybe include in the .podspec here as a build setting?

**Comment by paulb777** [comment]
@mikehardy Looks like both. 

I believe the `.podspec` here should match the library and framework requirements at https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFirestore.podspec#L103. 

Before that happens, the workaround for the pod client would be adding explicit linkages to the app.

**Comment by mikehardy** [comment]
Fantastic - thanks for the clarification @paulb777 - I am getting closer to the point where I could probably do an A2A for Android/Java items but Objective-C/Cocoapods[/Carthage/Swift/SPM]...I'll take all the help I can get :-)

**Comment by ben-xD** [comment]
It actually worked without doing anything when I tried it today, though it looks like some interesting discussion unfolded. It looks like @paulb777 means specifically the dependencies declared in the `FirebaseFirestore.podspec` from `firebase/firebase-ios-sdk` repo is not declared in `invertase/firestore-ios-sdk-frameworks`, e.g. `s.dependency 'gRPC-C++', '~> 1.28.0'`

I did not find the build times very long though, even without the optimisation from https://firebase.flutter.dev/docs/overview/#improve-ios-build-times
