### ISSUE TITLE
Multiple commands produce

### ISSUE THREAD

**Issue by guccisekspir** [invertase/firestore-ios-sdk-frameworks#31]
When I try this frameworks in my flutter project Xcode throw this error in archiving step.

`Multiple commands produce '/Users/cagrialtay/Library/Developer/Xcode/DerivedData/Runner-fkvkflrsozxbklbeilydskbmkijs/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/FirebaseInstanceID.framework': 1) Target 'FirebaseInstanceID-iOS10.0' has create directory command with output '/Users/cagrialtay/Library/Developer/Xcode/DerivedData/Runner-fkvkflrsozxbklbeilydskbmkijs/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/FirebaseInstanceID.framework' 2) Target 'FirebaseInstanceID-iOS14.4' has create directory command with output '/Users/cagrialtay/Library/Developer/Xcode/DerivedData/Runner-fkvkflrsozxbklbeilydskbmkijs/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/FirebaseInstanceID.framework'`

This is my pod file

`

> # Uncomment this line to define a global platform for your project
> # platform :ios, '9.0'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> 
> pod 'Firebase/Analytics'
> 
> def flutter_root
>   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
>   unless File.exist?(generated_xcode_build_settings_path)
>     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
>   end
> 
>   File.foreach(generated_xcode_build_settings_path) do |line|
>     matches = line.match(/FLUTTER_ROOT\=(.*)/)
>     return matches[1].strip if matches
>   end
>   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> end
> 
> require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> 
> flutter_ios_podfile_setup
> 
> target 'Runner' do
>   use_frameworks!
>   use_modular_headers!
>   
>   
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> 
> pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.3.0'
>   
> 
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
> end
> 
> target 'ImageNotification' do
>   use_frameworks!
>   
>   pod 'Firebase/Messaging'
> end

`

**Comment by mikehardy** [comment]
Without a reproduction I have to guess this is project-specific problem, as this was built with flutter in mind and works there as a semi-permanent integration for testing: https://github.com/FirebaseExtended/flutterfire/blob/331c60ce2abbfdcb8df57bd371d3a7c0b443d242/packages/cloud_firestore/cloud_firestore/example/ios/Podfile#L51
