### ISSUE TITLE
Using FirebaseFirestoreSwift for easy Codable Support

### ISSUE THREAD

**Issue by bks715** [invertase/firestore-ios-sdk-frameworks#47]
How Do I use the FirebaseFirestoreSwift pod with this precompiled version?

**Comment by paulb777** [comment]
A solution for this might depend on https://github.com/firebase/firebase-ios-sdk/issues/7819

**Comment by paulb777** [comment]
With Firebase 9.0.0, FirebaseFirestoreSwift is now included in the zip distribution
