### ISSUE TITLE
Firebase Remote Config is missing the required GCMSenderID - Flutter Project

### ISSUE THREAD

**Issue by giederloreto** [invertase/firestore-ios-sdk-frameworks#48]
Could you please, help me find a solution? This happen just when I build in IOS.... Android device works normaly! 

'Terminating app due to uncaught exception 'com.firebase.config', reason: 'Firebase Remote Config is missing the required GCMSenderID property from the configured FirebaseApp and will not be able to function properly. Please fix this issue to ensure that Firebase is correctly configured.'

I'm try use the Firebase remote config with Flutter on IOS too. But has a Crash when build the App.  I add the "GoogleService-Info.plist" normaly.  
Do you think there are error in the FirebaseRemoteConfig into SKD above?
Thank you!

**Comment by mikehardy** [comment]
I don't think this is the correct repository. It sounds like you are having trouble implementing FlutterFire, and should perhaps log the issue there, following their issue template?
