### ISSUE TITLE
Upstream SDK has altered tag format, breaking workflow script

### ISSUE THREAD

**Issue by mikehardy** [invertase/firestore-ios-sdk-frameworks#5]
This is an upstream issue I believe but it looks like they changed tag format?

`CocoaPods-6.27.0` is the new tag

**Comment by Salakar** [comment]
Thanks for the PR and headsup :) have merged, 6.27 should appear shortly 🤞

**Comment by mikehardy** [comment]
I think just in the last week I'm still ahead of the game with regard to time saved on compilation vs time spent during this whole upstream issue / PR creation :-)
