### ISSUE TITLE
cloud_firestore: ^3.2.1 compatibility issue

### ISSUE THREAD

**Issue by awagenfield** [invertase/firestore-ios-sdk-frameworks#53]
iOS build failing when the following line is added to Podfile

 **pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.2.0'**

Despite being much slower, excluding this line results in a successful build. 

Error output from Xcode build:
↳
    2022-07-02 17:24:29.747 xcodebuild[47717:6413181] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-07-02 17:24:29.747 xcodebuild[47717:6413181] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)

Keen to put this back when fixed to speed up testing!

**Comment by arnoutvandervorst** [comment]
When switching from the regular pod to this method, it removes some pods which I guess breaks the build:
Removing BoringSSL-GRPC
Removing Libuv-gRPC
Removing abseil
Removing gRPC-C++
Removing gRPC-Core

Error (Xcode): Framework not found FirebaseFirestoreSwift

**Comment by mikehardy** [comment]
Hmm - it may be that the podspec needs a bit of restructure? I haven't played with this yet and won't have time for a look for a while as I'm traveling - @Salakar maybe you've tried this recently? It seems like you had it working in fact and were just waiting for a 9.3.0 firebase-ios-sdk release ? 

If not, perhaps this needs a sync https://github.com/invertase/firestore-ios-sdk-frameworks/blob/19695456ec52caa91e4bc54430dfee6a29fec9ec/FirebaseFirestore.podspec#L19-L21

**Comment by r-dev-limited** [comment]
Any update on this ?

**Comment by mikehardy** [comment]
@r-dev-limited it's open source, so the updates you see are the ones that exist:

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

I am also interested in seeing updates, but haven't had time myself so I have not posted. What results did you see when you investigated?
