### ISSUE TITLE
9.4.0 or 9.4.1 is not available

### ISSUE THREAD

**Issue by Klabauterman** [invertase/firestore-ios-sdk-frameworks#57]
Can we make a new release for version 9.4.1? This is a pretty important updated since some annoying crashes from 9.3.0 were fixed.

**Comment by mikehardy** [comment]
Hi there! It appears based on the releases upstream that 9.4.1 is not available / not intended for anything but SPM, so 9.4.0 is the newest version I would expect here:

https://github.com/firebase/firebase-ios-sdk/releases/tag/9.4.1

There are other packaging issues upstream with 9.4.0 so it may be that those versions are not ever released correctly and we wait for 9.5.0 to release here, you may follow this issue for resolution or wait here: https://github.com/firebase/firebase-ios-sdk/issues/10103

**Comment by paulb777** [comment]
9.4.1 is exactly the same as 9.4.0 except for addressing a Swift Package Manager tagging issue.

**Comment by mikehardy** [comment]
Hey @Klabauterman - this is done now! Thanks for your patience and thanks to @paulb777 for the assist upstream

https://github.com/invertase/firestore-ios-sdk-frameworks/releases/tag/9.4.0
