### ISSUE TITLE
ld: library not found for -lBoringSSL-GRPC

### ISSUE THREAD

**Issue by rhisiart-cufflink** [invertase/firestore-ios-sdk-frameworks#7]
Without this library, I can successfully build a signed iOS app from both the terminal and within xcode but takes over an hour.

When I use this library, it whizzes through but fails at the last moment with the following message:

```
ld: library not found for -lBoringSSL-GRPC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

To use the library, I added the following line to the start of the `target 'Runner' do` method in the `Podfile`:

`pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.27.0'`

Note that it didn't matter whether I used `6.21.0` through to `6.27.0` or even if I left it out to use _master_.

... then did the following:
```
cd ios
rm Podfile.lock 
pod install --repo-update
cd ..
flutter build ios
```

Here's are my Firebase dart dependencies:

```
  cloud_firestore: ^0.13.4+2
  cloud_functions: ^0.5.0
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.3+1
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.13
```

... and finally `flutter doctor`

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.0)
```

**Comment by AdamMoffitt** [comment]
same issue

**Comment by esDotDev** [comment]
I get this error as well.

**Comment by rhisiart-cufflink** [comment]
Having parked this since June, I've given it another go and I no longer have an issue.

Here's are my new Firebase dart dependencies:
```
  cloud_firestore: ^0.14.1+3
  cloud_functions: ^0.6.0+1
  firebase_auth: ^0.18.1+2
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^7.0.3
```

... and `flutter doctor`:
```
$flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)

• No issues found!
```

One thing to note, is that I am no longer pulling in `firebase_core`.

**Comment by mikehardy** [comment]
great to hear! from June to now has been such a flurry of activity I'm not terribly surprised it resolved
