### ISSUE TITLE
[Archiving failing] [XCode 14.3] Multiple commands produce GoogleUtilities

### ISSUE THREAD

**Issue by RoyalCoder88** [invertase/firestore-ios-sdk-frameworks#72]
Hi friends,

I have a problem suddenly by archiving my app in XCode 14.3 I'm getting this strange error:

```swift

Showing All Errors Only

Prepare build
note: Building targets in dependency order
error: Multiple commands produce '/Users/razvanu/Library/Developer/Xcode/DerivedData/Runner-aeiwqtydtcicmbcjpyzoxtfwhzig/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
    note: Target 'GoogleUtilities-00567490' (project 'Pods') has create directory command with output '/Users/razvanu/Library/Developer/Xcode/DerivedData/Runner-aeiwqtydtcicmbcjpyzoxtfwhzig/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
    note: Target 'GoogleUtilities-54e75ca4' (project 'Pods') has create directory command with output '/Users/razvanu/Library/Developer/Xcode/DerivedData/Runner-aeiwqtydtcicmbcjpyzoxtfwhzig/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
```

I tried all of the solutions from the web nothing works for me 😦 please help/guide me with this issue, thanks in advance!

P.S: I'm able to build but not archive the app!

**Comment by iMrOwl** [comment]
hi, did you manage to solve the problem?

**Comment by vborbely** [comment]
> hi, did you manage to solve the problem?

I found that in some forum post that you have to add pod 'GoogleUtilities' into each of your target Pod file.

```
target 'Release' do
  pod 'GoogleUtilities'
  pod 'Firebase'
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
...
end
```

I hope this helps to someone.

**Comment by glonaldo70** [comment]
any solution?

**Comment by mikehardy** [comment]
I think we'll need a reproduction shared to troubleshoot this one
Does it happen when you just use the native firebase-ios-sdk and compile it vs this precompiled repackaging?
(if it works using firebase-ios-sdk instead of this repo, you can still enjoy fast builds with a compiler cache strategy like explained here https://reactnative.dev/docs/build-speed#use-a-compiler-cache )

**Comment by matteoSANE** [comment]
> > hi, did you manage to solve the problem?
> 
> I found that in some forum post that you have to add pod 'GoogleUtilities' into each of your target Pod file.
> 
> ```
> target 'Release' do
>   pod 'GoogleUtilities'
>   pod 'Firebase'
>   use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
> ...
> end
> ```
> 
> I hope this helps to someone.

This works for me. I added 'pod 'GoogleUtilities' to all targets.
Thank you @vborbely

**Comment by AnujMukhija-oyo** [comment]
'ios.useFrameworks' will its value be static or dynamic?
