### ISSUE TITLE
zsh: no such file or directory: https://github.com/invertase/firestore-ios-sdk-frameworks.git,

### ISSUE THREAD

**Issue by chanjungkim** [invertase/firestore-ios-sdk-frameworks#74]
I tried:

`pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.11.0'`

but I got that error. And `pod 'FirebaseFirestore` part works fine.

**Comment by mikehardy** [comment]
I don't believe that version (7.11.0) will work, the URL definitely works though, that should be an acceptable way to reference the repository
