### ISSUE TITLE
Failing with `Linker command failed with` when it previously worked

### ISSUE THREAD

**Issue by jonmountjoy** [invertase/firestore-ios-sdk-frameworks#78]
Hello,

On MacOS 14.0, Xcode 15.0.1 - this no longer works.  In fact, the app I have that used to compile against `10.15.0` retroactively fails to compile.

See this [example repo](https://github.com/jonmountjoy/bug_fb).

If you follow the instructions and build for iOS,  it will work.
If you modify the `ios/Podfile` and uncomment this line:

```
 # pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.17.0'

```

Then it fails with:

```
Failed to build iOS app
Error (Xcode): Undefined symbols:


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

<details><summary>Here's some of the verbose output:</summary>

```
[  +15 ms] Failed to build iOS app
[   +1 ms] Error (Xcode): Undefined symbols:

[        ] Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

[        ] "flutter ios" took 5,007ms.
[   +1 ms] Encountered error while building for device.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:665:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[   +1 ms] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
````

</details>

**Comment by mikehardy** [comment]
Possibly related - please see the discussion there for possible path forward until this is investigated - keeping one of these open is desired, so I'm okay with this remaining open: #79

**Comment by csbence10** [comment]
Hello,

same issue here

**Comment by mikehardy** [comment]
Hi @csbence10 - with apologies, that comment does not add much - I do see your reaction though so I definitely note another vote for this one. Did you see the comments on #79 ? I can't promise a timeline to resolve this but I can highly recommend ccache as described over there. I can't think of a stronger recommendation for using ccache over this pre-compiled / repackaged framework then the fact I'm the maintainer of this thing when I have time....and I use ccache :-). It's a superior solution.

I'll still try to investigate this when I do have time, but head over to #79 and check out the link I posted to a ccache recipe / style that works for compiler acceleration.

Cheers

**Comment by mikehardy** [comment]
#79 was re-opened and having two issues tracking the same thing really splits the work, so I'm going to close this one now - but it is not with prejudice or anything 😄 - 79 has seen a fair bit of investigation. Looks tough to solve but potentially can be done.

I still personally recommend ccache, but if we can keep this working as a different solution, we will...
