### ISSUE TITLE
[Xcode 15.+] Can't build app with v10.18.0 due to Swift version

### ISSUE THREAD

**Issue by xmasux** [invertase/firestore-ios-sdk-frameworks#84]
When executing `flutter build ipa` I'm getting the following error:
```
Swift Compiler Error (Xcode): Failed to build module 'FirebaseFirestore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version
5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a
toolchain which matches the SDK.
/Users/mariusmergenthaler/Library/Developer/Xcode/DerivedData/Runner-enukuzpxjzrxptdxkuyiyiabypdp/Build/Intermediates.noindex/ArchiveIntermediates/production/Buil
dProductsPath/Release-production-iphoneos/XCFrameworkIntermediates/FirebaseFirestore/Base/FirebaseFirestore.framework/Modules/FirebaseFirestore.swiftmodule/arm64-
apple-ios.private.swiftinterface:0:0
```

AFAIU this is due to my Xcode version. However, I can't downgrade to Xcode 14.1 as it is no longer supported on macOS Sonoma

**Comment by mikehardy** [comment]
Hi there! You have not posted any version information so it's not possible to help
https://stackoverflow.com/help/how-to-ask

Please note that the likely answer here if versions *were* included is "you need to update firebase-ios-sdk versions", which likely implies updating your FlutterFire (or react-native-firebase if you are using react-native) to current versions. At which point you will likely run in to #79 and the current suggestion is to use ccache, discussed here #82 

I can state without reservation that current versions of Firebase compile fine with current versions of firebase-ios-sdk, but I can also say that #79 will completely prevent you from using the most current version

Your specific compilation issue won't result in a change here though so is not actionable as a repo issue
