### ISSUE TITLE
How to use this strategy in a Flutter module?

### ISSUE THREAD

**Issue by tomsun** [invertase/firestore-ios-sdk-frameworks#9]
> Integrating is as simple as adding 1 line to your main target in your projects Podfile

How to use this in a module? ( `flutter create -t module ...` ): Those don't have a Podfile themselves

For production, I suppose you could add it to a Podfile of every app that depends on the module.
For dev, I suppose you can modify the module's .ios/ dir, even though it is ephemeral.

Both of those can be somewhat inconvenient when you try to create an easy-to-use module:

Would it be possible to apply firestore-ios-sdk-frameworks's prebuild strategy from the .podspec of a plugin ( `flutter create -t plugin ...`) that the module depends on in addition to `cloud_firestore`? i.e. if firestore-ios-sdk-frameworks itself was a plugin you depended on in pubspec.yaml.

Or would one have to fork `cloud_firestore` and related plugins and have them themselves ship prebuilt frameworks in order to get that to work?

**Comment by Salakar** [comment]
Unfortunately CocoaPods only supports this kind of override thing at the Podfile level, Podspecs don't support this - I tried originally to do this for `cloud_firestore` but in the end this repo + adding to Podfile was the only viable solution.

If this is applied in a users Podfile it overrides any podspec that is using Firestore so it should still in theory already apply to any other custom flutter modules that are using Firestore. If the users of your module are already using `cloud_firestore` then this seems ok to me?

**Comment by tomsun** [comment]
Ok, thanks for the reply! 

We happen to not use cocoa pods in a particular app that uses the module. We use `flutter build ios-framework` and drop in the frameworks in the app (programmatically) [as per the add to app guide](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode). Haven't found a way for that command to just build `App.framework` to speed up consecutive runs though, so it is always rebuilding everything and Firestore takes forever as usual, hence looking at your repo (using it in another regular Flutter project with great results). (Maybe I'll try a local mod of cloud_firestore & co next, to somehow only include the dart parts on consecutive runs of `flutter build ios-framework`)

Do you know whether FirebaseExtended/flutterfire are considering going down the prebuilt route themselves?
