### ISSUE TITLE
No GitHub release for 10.24.0

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/firestore-ios-sdk-frameworks#99]
There is no release for the 10.24.0 version

**Comment by nilsreichardt** [comment]
Thanks, I know but it's missing on https://github.com/invertase/firestore-ios-sdk-frameworks/releases. Only nit-picking nothing dramatically

**Comment by russellwheatley** [comment]
We're now on `v10.27.0` which has been released 🙏
